### ISSUE TITLE
Injecting services in user controls

### ISSUE THREAD

**Issue by rbasniak** [maythamfahmi/WpfSampleDi#1]
Hi,

I tried your example, and it works great until I needed to add an user control to the project. 

If I inject something in the user control, the application doesn't start. I registered the usercontrol as a singleton in the app.xaml.cs together with the MainWindow.

Do you know if this is possible?

**Comment by maythamfahmi** [comment]
I am not sure what you want to reach. As far as I know, you can not just inject UserControl as singleton, the way you do. But you have several options, one easy way is that we need to understand the life cycle of WPF and the class hierarchy, that said I might find time to come with other solutions, but for now only this one. When you start the application the first method is in MainWindow `InitializeComponent()` called. This method will initialize UserControl class first. so what can we do with that. Here is my suggestion:

in main windows
```
public readonly ILogBase LogBase;

public static MainWindow AppWindow;

public MainWindow(ILogBase logBase)
{
    AppWindow = this;
    LogBase = logBase;

    InitializeComponent();
}
```
And in your user control

```
private readonly ILogBase _logBase;

public UserControlExample()
{
    InitializeComponent();

    if(MainWindow.AppWindow?.LogBase != null)
        _logBase = MainWindow.AppWindow.LogBase;

    TestMethod();
}
```
I have updated the [repo ](https://github.com/maythamfahmi/WpfSampleDi) with this example.

**Comment by rbasniak** [comment]
Thanks for the reply. This works very well.

**Comment by pekspro** [comment]
@maythamfahmi, I suggest to instead having the ServiceProvider globally accessible. Like as a static in the App class:

     public partial class App : Application
     {
        public static IServiceProvider ServiceProvider;

Then you could use this in the user control to get the services you want:

    public partial class UserControlExample: UserControl
    {
        public UserControlExample()
        {
            InitializeComponent();

            DataContext = App.ServiceProvider.GetRequiredService<ILogBase>();
        }

This way the user control is not dependent on the main view.

**Comment by maythamfahmi** [comment]
@pekspro sorry for being late. I do not think it is a good idea to use static for dependency injection. If you find it solving your approach and ensure you do not get side effect. Honestly I have not tried that way.

**Comment by Lj-dog** [comment]
> [@pekspro](https://github.com/pekspro) sorry for being late. I do not think it is a good idea to use static for dependency injection. If you find it solving your approach and ensure you do not get side effect. Honestly I have not tried that way.很抱歉迟到。我认为使用 static 进行依赖注入不是一个好主意。如果您发现它解决了您的方法并确保您不会产生副作用。老实说，我没有尝试过那样。

but if '_serviceProvider' is private readonly . Then mean I can't use 'GetService' in other class to get service !?   
have you ever had the problem
