### ISSUE TITLE
System.IO.IOException: Could not found the resource aponstartup

### ISSUE THREAD

**Issue by DSBRBrasil** [maythamfahmi/WpfSampleDi#2]
Hi dude !
What I did it wrong ?

**Comment by maythamfahmi** [comment]
Hi,
Thank you for checking the repo,
I am not sure, but looks like you have naming issue, i call it AppOnStartup and not ApOnStartup, maybe you need to recheck it. If you follow my example it should work, you can also download my example and build on top of it.
